### PR TITLE
Updates to README and drop Julia 0.5

### PR DESCRIPTION
**Pull request by mirestrepo**
1. Basic update to the documentation/badges in the readme
2. Update to Julia 0.6 and take care of deprecated warnings

### CODE REVIEW

**Comment by mirestrepo** [comment]
The failing test in Travis is not related to code, but rather to a CURL failure to get Julia...

**Comment by mirestrepo** [comment]
@bicycle1885 @Ward9250 We are part of the Biomedical Informatics Center at Brown University. About a year ago, I started a package https://github.com/bcbi/BioMedQuery.jl that works with Entrez and other APIs. I am in the process of restructuring the package to be more modular. Instead of keeping the package separate from the BioJulia community I am hoping to start using BioServices and contribute to it whenever there is an opportunity. 
We use the tools on our BioMedQuery very often. For us to switch to BioServices, we need to know that we can keep an active development environment/discussion. I know you are part of the creator/maintainers related to this part of BioJulia, so I'd like your opinion on whether our plan of contributing to BioServices is of interest to your community.

**Comment by Ward9250** [comment]
Hi @mirestrepo, contributing to BioServices is definitely of interest to the community. We've had several attempts to create packages for working with these APIs which fit well into the BioJulia "ecosystem" packages, but I think much improvement can come from people who use the API's more often. 

Since Bio.jl got decentralised into BioSequences.jl, BioStructures.jl, ... , and BioServices.jl we are hoping that individuals will gravitate towards the packages they use more often and have more experience with, and that some of those individuals will ask to join the BioJulia membership to be a maintainer of said packages they gravitate to or contribute to the project (on our other packages READMEs have badges with named BioJulia members on them who are largely responsible for looking after it). 

We would be thrilled if you would be such a member and help maintain and improve BioServices.jl.

**Comment by mirestrepo** [comment]
@Ward9250 I would certainly be more than thrilled to help grow and maintain BioServices.jl. Let me know what needs to happen to move forward. I'm happy to take care of the basic updates to Julia 0.6, docs, official tag and help grow it from there.

**Comment by bicycle1885** [comment]
@mirestrepo Thank you for your contribution! We really appreciate contributions from serious users. Of course, if you wish, we will add you to the BioJulia members so that you can freely update the package.

The change you made looks good to me. I'm going to merge it if no objections, and then tag and release a first version since it is not yet released.

**Comment by mirestrepo** [comment]
@bicycle1885 Sounds great. Yes, I'd love to be part of the BioJulia members. Are there any "guidelines" that new maintainers should be aware of? Or is generally okay to update packages directly without creating pull requests?

**Comment by bicycle1885** [comment]
We use [GitHub Flow](https://guides.github.com/introduction/flow/) development model in most cases. Once a package is placed in BioJulia org., we should follow the guideline of GitHub Flow. GitHub Flow recommends creating pull requests for any changes so that we can keep the master branch healthy using continuous integration services. We may need some docs on our development style.

**Comment by mirestrepo** [comment]
Before we completely close all this thread, what is the process to be added as a BioJulia member? I will then follow the GitFlow for updates, i.e open pull request to make sure tests are passing and to give an opportunity for discussion ... and if all okay and no obstructions I'll merge.

**Comment by Ward9250** [comment]
@mirestrepo There's no specific formal process other than letting us know you want to contribute and we will add you.

I've listed information about being a member and contributing to BioJulia at http://biojulia.net/Contributing/latest

With the new package organisation we'd like members of BioJulia to take on one or more packages as a dedicated maintainer. As I mentioned previously. And currently BioServices does not have one - I think you would be the ideal candidate. 

Beyond contributions to the package with PRs, the maintainer is also involved in making releases, helping resolve conflicts and so on. I've written more about dedicated package maintainers here: 
http://biojulia.net/Contributing/latest/policy/biojulia_organisation.html#The-package-ecosystem-and-Maintainers-1

We use GitHub flow a lot as @bicycle1885 suggested as we maintain packages. This has also been written about in the documentation here:

http://biojulia.net/Contributing/latest/help/branching_guide.html

This describes how to add new features or code - branching, making a PR against master, waiting for tests and discussion then merging.

But also it describes preparing a release of the package with a release branch or an urgent hot-fix of a critical bug. These two things are things dedicated package maintainers will worry about that casual contributors won't need to. The guide can be improved I think so any questions and comments to help me make it better are appreciated.

Other than that, if you have any Q's, just ask, I'll add you to the team today, if you're happy to join and maintain & develop this package.

**Comment by mirestrepo** [comment]
@Ward9250 I all sounds good. I would be more than happy to join as a dedicated maintainer of BioServices. So feel  free to add me.
Thanks!

**Comment by Ward9250** [comment]
@mirestrepo Great! Just sent you an invite!

**Pull request merged**
