### PR TITLE
Update EUtils manual

### PR DESCRIPTION
**Pull request by mimame**
# Update EUtils manual

## Types of changes

* [X] :bug: Bug fix (A non-breaking change, which fixes an issue).

## :ballot_box_with_check: Checklist

- [X] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [X] :ok: All changes should be compatible with the latest stable version of Julia.

### CODE REVIEW

**Comment by kescobo** [comment]
Why does this lose all of the coverage of `src/umls.jl`? Is that a bug, or something with doctests?

**Comment by mimame** [comment]
@kescobo I don't know what is happening. I've only updated the EUtils markdown file and that's all

**Comment by kescobo** [comment]
Right - I saw that. It makes no sense...

**Comment by mirestrepo** [comment]
That is because UMLS build depends on environment variables with credentials that are not shared to PRs

**Pull request merged**
