### PR TITLE
WIP: Add EMBL-EBI Proteins REST API

### PR DESCRIPTION
**Pull request by BioTurboNick**
## Types of changes

This PR implements the following changes:

* [x] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail

- If you have implemented new features or behaviour
  - **Provide a description of the addition** in as many details as possible.
Implementation of the EMBL-EBI Proteins API (UniProt): https://www.ebi.ac.uk/proteins/api/doc/

  - **Provide justification of the addition**.
  It's a huge database with lots of information, really important to have access to it.

  - **Provide a runnable example of use of your addition**.
```
using EBIProteins
ebiproteins(accession = "P08069", contenttype = "text/x-fasta")
```

## :ballot_box_with_check: Checklist

- [ ] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [ ] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [x] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [x] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by kescobo** [comment]
Sorry about test failures, I think travis isn't configured anymore. I'm assuming your tests pass locally, and once #36 is merged, would be good to rebase off of that.

**Comment by BioTurboNick** [comment]
No worries, I don't have any tests at all just yet 😆. That will be fixed.

**Comment by BioTurboNick** [comment]
Looks good to go!

**Review by kescobo — APPROVED** [review]
Looks great, thank you! I didn't _really_ review it, but tests look good to me, and it's only adding things, so don't see any reason to hold it up!

**Comment by BioTurboNick** [comment]
Great, thanks!

**Pull request merged**
