### PR TITLE
Add more builds to the Travis matrix

### PR DESCRIPTION
**Pull request by ibacher**
This is a really simple PR to add more versions of Julia to the build matrix as well as to run the Windows builds on Travis instead of AppVeyor.

## Types of changes

This PR implements the following changes:

* [ ] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).
* [x] :wrench: Continuous integration improvement

## :clipboard: Additional detail

Previously, builds have been run using Julia 0.7, 1.0 and nightly on macOS and Linux and Julia 0.7 on Windows. The macOS and Linux builds were run on Travis; the Windows builds were run on AppVeyor.

With this PR, builds are being run using Julia 0.7, 1.0, 1.2, 1.3, and nightly on macOS, Linux, and Windows. All of these builds are run on Travis.

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [ ] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by kescobo** [comment]
Great, thanks for doing this! IMO we should allow failures on the release candidate (1.3) as well as nightly. Probably won't break, and it's definitely good to run that build, but as a matter of principle I think it's ok to say we only support the current and LTS releases. Can probably get rid of 0.7 at this stage as well right? 

As an argument against myself, the `[compat]` section of the `Project.toml` says the package supports all julia >=0.7, and if we want to keep that promise, should probably also test 1.1, and not allow failures on 1.3. 🤷‍♂

**Comment by ibacher** [comment]
Those are great points. I'll allow failures on 1.3 and add in 1.1.

I'm perfectly happy with dropping Julia < 1.0, but since this change wouldn't otherwise require a new release,  I didn't want to make that change 😄.

**Comment by mirestrepo** [comment]
@ibacher Can you remove support for 0.7?

**Comment by ibacher** [comment]
Not at all! I've committed those changes to this PR.

**Comment by mirestrepo** [comment]
Thanks. Also could we get rid on appveyor? Travis is doing Windows now

**Comment by ibacher** [comment]
@mirestrepo That's the main point of this PR. I've deleted the appveyor.yml file, but I don't have the permissions to remove it from the webhook.

**Comment by kescobo** [comment]
So, one travis build failed because of 

```
  HTTP.ExceptionRequest.StatusError(429, "GET", "/entrez/eutils/egquery.fcgi?term=%28Asthma%5BMeSH%20Major%20Topic%5D%29%20AND%0A%28%221%2F1%2F2018%22%5BDate%20-%20Publication%5D%20%3A%0A%223000%22%5BDate%20-%20Publication%5D%29", HTTP.Messages.Response:

  """

  HTTP/1.1 429 Too Many Requests
  Date: Tue, 03 Sep 2019 13:24:26 GMT
  Server: Finatra
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Content-Security-Policy: upgrade-insecure-requests
```

So it might be worth adding some pauses to the test suite.

The Mac builds of julia 1.0 and 1.1, AND Windows 1.2 are failing because of

```
espell: Error During Test at /Users/travis/build/BioJulia/BioServices.jl/test/eutils.jl:137

  Got exception outside of a @test

  MethodError: no method matching getindex(::SubString{String}, ::String)
```

Which is really confusing - why would this work on some julia versions and not others (and why would it be different julia versions on mac and windows?

**Comment by kescobo** [comment]
I wonder if these errors are related somehow - if there's a Too many requests error, and then calls in other builds are getting nonsense returns instead. The failing function [is here](https://github.com/BioJulia/BioServices.jl).

**Comment by ibacher** [comment]
So the Travis concurrency setting is probably the best way to get builds to only run one at a time (see [the Travis docs on this](https://docs.travis-ci.com/user/customizing-the-build#limiting-concurrent-jobs)). The tests all already have a .3 second delay built-in which approximately ensures we don't go over the 3 requests / second limit.

@kescobo: I'm kind of guessing the same thing. I think the line that's failing is [this one](https://github.com/BioJulia/BioServices.jl/blob/b9600ce859c60d7a7d6c948daa8945e320395f63/test/eutils.jl#L144), mostly because that's the one line that's substantially different from the "egquery" tests, which throw the comprehensible API rate failure.

**Comment by kescobo** [comment]
@ibacher Good idea - I just set concurrent builds to 1 and triggered a new build. Let's see if that helps. I don't seem to have the ability to change the appveyor settings though.

**Comment by kescobo** [comment]
Interesting - last build made it *almost* all the way, but nightly failed with that same method error right at the end...

**Comment by ibacher** [comment]
Yeah... if it was only the nightly on Windows, I wouldn't be too worried about it, but trying again [hit the same error](https://travis-ci.org/BioJulia/BioServices.jl/jobs/580393612#L194) on Julia 1.1 on Mac.

**Comment by ibacher** [comment]
The quick fix is probably it up the sleeps between tests to 0.4 seconds (since 0.3 might conceivably hit the 3 requests / second limit). The real fix would be something that addresses #14.

**Comment by kescobo** [comment]
Again, 1 fail from the string method error, but it's a different one than previous builds. I think this should be merged this and wait for #14 to fix.

**Comment by mirestrepo** [comment]
@ibacher Do we rebase to use the retry and not the explicit sleep on the tests? Is that your idea?

**Comment by ibacher** [comment]
@mirestrepo Yes. I added #26 to try and work around the build failures here. Both of these work on my machine, but that's not worth much. I'll try to get to doing the rebase and push to this branch.

**Comment by mirestrepo** [comment]
They also work on enough build that I'm comfortable merging. I know UMLS is temperamental. I'll be on the lookout for the rebase to merge

**Comment by ibacher** [comment]
@mirestrepo I've done the rebase and force-pushed it. The tests basically work, but it looks like something needs to be tweaked for the documentation to build.

**Comment by mirestrepo** [comment]
Ugh.. docs, right. This still uses an old config of docs, when documenter used to use markdown and material theme was an easy addition. 

I think it needs to be reverted to default theme.... 
I'll try to look into it

**Comment by kescobo** [comment]
@ibacher I _think_ this PR is obviated by #36, is that right?

Sorry to have you do all of this work and then not get it merged :-(. Really appreciate you persisting, but it looks like most of the community is moving towards github actions. Let me know if there's something in here that could be preserved.

**Comment by ibacher** [comment]
@kescobo That's perfectly fine! I agree that this work is superceded by that PR. In any case, I clearly haven't had the time to fix this up, so thanks for your work here!

**Pull request closed without merging**
