### PR TITLE
Project file updates

### PR DESCRIPTION
**Pull request by BenJWard**
## Types of changes

This PR implements the following changes:
_(Please tick any or all of the following that are applicable)_

* [ ] :sparkles: New feature (A non-breaking change which adds functionality).
* [x] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail

This PR updates some project files ~~and uses EzXML again now that the troubles installing it
have been fixed~~.

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [x] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [x] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by BenJWard** [comment]
@mirestrepo I'm getting IO errors for one of the epost tests, is that just a service down or have I done something incorrectly?

**Comment by mirestrepo** [comment]
@BenJWard 

**Thanks**  for all the nice additions!

**About restoring EzXML** what are your reasons to do so? XMLDict makes the code very readable. For large XML parsing, EzXML would be much more efficient but, but EUtils only parses short HTML responses. If you think EzXML is a be a better dependency to have, I'm open to it though.

**About failing tests** I think the server responses intermittently fail because we may be exceeding the 3-calls/per second limit. I have added time delays to the tests - that fixed it consistently for my locals test, let's wait for travis.

**Comment by BenJWard** [comment]
EzXML is your call, I only restore it here as the PR that used XMLDict gave me the impression it was temporary whilst EzXML has it's install issues sorted. If you want I can go back and leave XMLDict in if you've found you actually prefer it as a dependency.

**Comment by mirestrepo** [comment]
Let’s stay with XMLDict. I like having easy access to the fields of the http responses instead of parsing them manually.

**Comment by BenJWard** [comment]
Ok I'll put XMLDict back in a short while, and this will basically be a project files PR then.

**Comment by BenJWard** [comment]
@mirestrepo Oh gawd I just noticed the timeout commit isn't there. Are you able to push it back from your local clone?

**Pull request merged**
