### PR TITLE
Modernize docs and CI

### PR DESCRIPTION
**Pull request by kescobo**
This PR is intended to modernize and update unit testing and Documentation building using Github CI. Refs #35 #31 #32 

- [x] Switch to github actions instead of travis / appveyor
- [x] Update Documenter build
- [x] Add compat to Project.toml
- [x] update failing tests (some look to be on pre-julia 1.0 syntax?

Some open questions, having started in on this:

- I don't know what the `make.yml` stuff was for - maybe old documenter requirements? Unclear if all of that is necessary anymore, but I haven't removed it yet
- The current styling of the docs isn't standard, is keeping it the same desirable?
- For package compat, I've currently added the most recent version of each package circa end-of-2018 when the last release was made, but as tests were failing even then, I don't know if that makes sense. I'll try to test up to current versions once I get tests working

### CODE REVIEW

**Comment by kescobo** [comment]
Looks like the failure was because of compat holding HTTP at 0.7, and that version has old regex syntax. Changing to 0.8 has tests passing locally

**Comment by kescobo** [comment]
New docs preview can be seen here: https://biojulia.net/BioServices.jl/previews/PR36/

**Comment by kescobo** [comment]
And it looks like stuff still works with newer compat, at least locally. Failures on 1.6 are because that version can't be found - it was just tagged yesterday, so might take some time to propagate. I'm testing locally on 1.6.0

**Comment by kescobo** [comment]
Given that this works on Julia 1 and on nightly, plus on one of the 1.6 builds, and the others are failing because it couldn't find the version, I'm inclined to get this merged. I removed doctests from the list of to-dos, since I don't have time for that at the moment and this is complete as-is. @mirestrepo Can you take a look?

**Comment by kescobo** [comment]
@jakobnissen Can we get this merged? I'm happy to take on some maintainer duties for this repo if helpful

**Comment by jakobnissen** [comment]
I can't merge this - not sure why. It says the "Package maintainer" group has write access - that includes you and me. And yeah, it would be great if you can maintain this! :) Unless @mirestrepo is still active in BioJulia?

**Comment by mirestrepo** [comment]
I am no longer active in this community :( ... I keep hoping that I will be able to carve out time, but I likely should be removed as a maintainer. It's really nice to see this package getting some love!

The PR can't be merged because it's labeled as a draft. I think all it needs to happen is for @kescobo to label it as "ready for review"

@kescobo the `makedocs.yml` was there because I believe the old docs used material mkdocs and old documenter didn't support it out of box.... in any case you shouldn't need it if you're going with BioJulia's standard docs.

One last thing is that someone should probably get an account with UMLs and put a token as a secret for UMLS tests to run. If no credentials are found those tests are skipped, which is fine in the short term, but may be nice to have them run...

**Comment by jakobnissen** [comment]
Sad to hear, but that happens now and again with open source work :) @kescobo I've made you admin of this repo

**Comment by kescobo** [comment]
Oh, derp... Forgot about that! Thanks @mirestrepo for all your work in the past, and sorry you don't have time for it anymore, but totally understand. Here's hoping you'll be able to come back soon!

**Pull request merged**
